### ISSUE TITLE
Downloads implementation

### ISSUE THREAD

**Issue by fwicht** [jrudio/go-plex-client#36]
It would be great if the client could also include the Plex download feature.

**Comment by fwicht** [comment]
I'd be happy to implement it. In my understanding it simply consists in downloading the Media[].Part[]?

**Comment by jrudio** [comment]
Is this the download feature you are talking about?

![Screenshot 2021-11-06 132208](https://user-images.githubusercontent.com/6628361/140622836-4398c6ef-fa97-4edf-9f80-894d6ddecd27.png)

If so, then yes I think you can use the information in ` Media[].Part[]` to download. This is what the Plex Web client does for the above feature, it sends a GET to the `/library/parts/12/1625693900/file.mkv?download=1` endpoint.
![Screenshot 2021-11-06 132214](https://user-images.githubusercontent.com/6628361/140622837-b4312d28-2c5d-405f-b4cf-15d2ee10b3f2.png)

I would have to investigate some more to give a better answer. But I'm currently working on #34 😢

**Comment by jrudio** [comment]
Also, yes that would be a great feature!

**Comment by fwicht** [comment]
Yes! This is exactly what I'm talking about. I just made a pull request #37

**Comment by jrudio** [comment]
Love the code on that contribution! Closing because merged. Thanks again!
