### ISSUE TITLE
Ability to download with folder hierarchy

### ISSUE THREAD

**Issue by fwicht** [jrudio/go-plex-client#39]
This would be a nice addition to the download feature if we could (re)create the folder hierarchy using the Grandparent and Parent fields. Downloading media.ext would be put in

`Grandparent/Parent/media.ext`.

This would be quite useful when downloading TV Shows for example

`"Game of Thrones"/"Season 01"/"01 Winter is Coming.mkv"` or even for Music
`"Oliver Koletzki"/"The Arc of Tension"/"1-01 A Tribe Called Kotori.flac"`.

**Comment by fwicht** [comment]
In my opinion, this could be easily implemented by adding a boolean field `shouldRecreateFolderHierarchy` to the Download function.

**Comment by jrudio** [comment]
This sounds very handy! Not too important but maybe we can shorten the variable name? It does get the point across but seems rather lengthy.
And yes, I agree that modifying the existing download function with a flag would be best.

**Comment by fwicht** [comment]
I agree about the variable name, would you have some recommendation?

**Comment by fwicht** [comment]
I simply came up with `createFolders` as you can see in the pull request #40.
